### PR TITLE
v1.3

### PR DESCRIPTION
**Pull request by Conroman16**
Hey DasKeyboard guys, I did some much needed updating work on the ICMP Ping applet.  When I initially submitted it back in April, @fabiendv mentioned that it would be nice if the applet could generate its own gradients instead of asking a user to manually specify one.  Well, the other day I sat down and just hammered it out really quick based on the [tinygradient](https://www.npmjs.com/package/tinygradient) library, and then I cleaned it up this morning since I had the day off today :slightly_smiling_face:.  What do you guys think?

### CODE REVIEW

**Comment by Conroman16** [comment]
I pushed in one more tiny little feature (fix?) on this that I thought of once I stepped away.  Instead of generating the gradient array on each run, I'm now generating it just once in the constructor.  I've tried to make this applet as light as possible so it seems like a much better idea than generating it on each run.  I'm not sure how much extra weight tinygradient really adds, as the dependency chain is extremely short and are all libraries I know to be focused on being very light, so this might be something that could come back in the future as part of a 'feature' I have stewing in the back of my mind, but we'll see what I end up having time for.  Until then it's relegated to a one-time operation for performance sake

**Comment by Conroman16** [comment]
Made another small change after having a random idea while I was working on something else.  It occurred to me that tinygradient returns an array of tinycolor objects.  Tinycolor objects have a `toHexString()` method so I adjusted the hex converter function to just call that instead of calculate the hex manually via bitshifting, as I may struggle to understand how that shifting operation works when I come back to this code next time

**Comment by Mubramaj** [comment]
Hi @Conroman16, 
I am sorry for the late reply. 
I am looking at your changes right now. I noticed that there is no tests. Can you please add some tests and push it in the same pull request. You can use Mocha. There is test example for every applet in the marketplace.
I will then merge everything and deploy the new version of your Applet.
Thank you for your contribution and sorry again for the delay.

Best,
Ahmed

**Comment by Conroman16** [comment]
I'm pretty much out of time to work on this for a while but we'll see what I can do.  Writing a test harness is not what I had in mind before this went for an update but I suppose it's "good practice"

**Comment by Conroman16** [comment]
Alright I figured it was probably now or never so I stayed up and wrote something up.  Hopefully this is sufficient, as my brain is tired ~and tests are the worst~ :laughing:

**Comment by Mubramaj** [comment]
Hi @Conroman16 ,

I released the new version on the Marketplace. I decided to increment the version number to `2.0.0` because there is breaking changes in the user configuration.
This way when users will upgrade your applet they will go through the input configuration again.
Best,
Ahmed

**Comment by Conroman16** [comment]
Hey @Mubramaj that sounds good by me.  I suppose I didn't realize users wouldn't be pushed through the config pages on a minor version update.  Good catch!  My project that I was supposed to get started on tonight didn't end up happening so you might see some more activity from me in the near future.

Thank you!

**Pull request merged**
